spring.application.name=library_v3_back
server.port=8083


# 本地 docker 的 mariadb
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3309/MariaLibraryV3?serverTimezone=Asia/Taipei&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=123456789

# aws rda 的 mariadb mariadb0825.cfyowy8k6wu3.ap-southeast-2.rds.amazonaws.com(已刪除，沒錢)
# azure 部署網址：library0825-eubedfhpd3epa7bp.japaneast-01.azurewebsites.net
# 已連接 github 並自動部署，阿怎麼沒變
#spring.datasource.url=jdbc:mariadb://mariadb0825.cfyowy8k6wu3.ap-southeast-2.rds.amazonaws.com:3316/MariaLibraryV3Cloud
#spring.datasource.username=admin
#spring.datasource.password=B47tydnf3939
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 可以在 console 查看由 Spring Data JPA 所自動生成的 SQL 語法
spring.jpa.show-sql=true

# security 配置步驟 7: 建立 JWT 工具類別 (JwtUtil.java)
# 這個類別負責 JWT 的生成、驗證和資訊提取。
# JWT 配置
# JWT 過期時間，例如 1 小時 (3600000 毫秒)，方便測試先無設限

jwt.expiration=3600000000